# image: gitpod/workspace-dotnet:latest
#image:
#  file: .gitpod.Dockerfile
#image: gitpod/workspace-full:latest
#image: mcr.microsoft.com/dotnet/nightly/sdk
image: codeconsultants/dotnet-sdk:6.0

tasks:
  - name: Create dev certificate for HTTPS
    init: dotnet dev-certs https # NB: Could add `gp sync-done create-cert`
  - name: Build and watch-run aspnet application/API
    init: | # Could add `gp sync-await create-cert`
      dotnet restore
      dotnet build
    command: dotnet watch run

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  #- port: 8080
  #  onOpen: open-preview
  - port: 5113 # HTTP
    onOpen: open-browser
  #- port: 7024 # HTTPS
  #  onOpen: ignore

vscode:
  extensions:
    - muhammad-sammy.csharp
    - AmazonWebServices.aws-toolkit-vscode
    - GitHub.copilot
    
